services:

    Troopers\CronBundle\Reporting\ReportManager:
        class: 'Troopers\CronBundle\Reporting\ReportManager'
        arguments:
            - '@kernel'

    Troopers\CronBundle\Cron\Manager:
        class: Troopers\CronBundle\Cron\Manager
        public: true
        arguments:
            - '@kernel'
            - '@Troopers\CronBundle\Reporting\ReportManager'

    Troopers\CronBundle\Command\CronRunCommand:
        class: Troopers\CronBundle\Command\CronRunCommand
        tags:
            - { name: console.command }